#
# setupenv-diag.sh
#
# Environment variables: generated by diag.sh
# - diag.sh generated and export environment variables to be used by test programs: 
# - user may override these generated variables under special conditions
# For example, for tz170w system, env variables generated are:
#
# DIAG_SYS_TYPE=“tz170”  # main system name
# DIAG_SYS_TYPE_EXTRA=”w”  # this maybe empty
# DIAG_SYS_REV=01    #  always two digits
# DIAG_LOG_PATH=”log”
# DIAG_LOG_FILE=”msg-${DIAG_SYS_TYPE}${ DIAG_SYS_TYPE_EXTRA}-${DIAG_SYS_REV}.log”
#

export DIAG_ROOT_PATH="/diag"
export DIAG_VERBOSE=0

# run mode 0: not running in "dialog" 
export DIAG_RUN_MODE=0

if [ "$1" = "-v" -o "$1" = "--verbose" ] ; then 
    export DIAG_VERBOSE=1
    shift 1
fi 

if [ "$1" = "-vv" ] ; then 
    export DIAG_VERBOSE=2
    shift 1
fi 

if [ "$1" = "-vvv" ] ; then 
    export DIAG_VERBOSE=3
    shift 1
fi 

sys_prodcode=`sysinfo prodcode`
sys_type=`Prodcode_2_Sys_Type ${sys_prodcode}`
if [ "${sys_type}" = "error" ] ; then 
    exit $?
fi

export DIAG_SYS_TYPE="$sys_type"

# TODO: hard coded to 01 for now!!! 
export DIAG_SYS_TYPE_EXTRA=""
export DIAG_SYS_REV="01"

export DIAG_LOG_PATH="${DIAG_ROOT_PATH}/log"
export DIAG_LOG_FILE=”${DIAG_LOG_PATH}/msg-${DIAG_SYS_TYPE}${DIAG_SYS_TYPE_EXTRA}-${DIAG_SYS_REV}.log”

mkdir -p ${DIAG_LOG_PATH}
if [ $? -ne 0 ] ; then 
    echo -e "ERROR: mkdir ${DIAG_LOG_PATH} failed!"
    exit $?
fi 

if [ ${DIAG_VERBOSE} -ne 0 ] ; then 
    Diag_Dump_Env_Vars
    read -p "Press Enter to continue"   
    # read -n 1 -s -r -p "Press any key to continue"
fi 
